name: flutter_clean_architecture_reference_implementation

workspace:
  - app/
  - core/common/
  - core/data/
  - core/domain/

environment:
  sdk: ^3.10.4

dev_dependencies:
  melos: ^7.1.0

melos:
  command:
    bootstrap:
      environment:
        sdk: ^3.10.4

      dependencies:
        cupertino_icons: ^1.0.8
        http: ^1.6.0
        logger: ^2.6.1

      dev_dependencies:
        flutter_test:
          sdk: flutter
        flutter_lints: ^6.0.0
        melos: ^6.3.3
